--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Ubuntu 15.2-1.pgdg20.04+1)
-- Dumped by pg_dump version 15.2 (Ubuntu 15.2-1.pgdg20.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Addresses; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Addresses" (
    "Id" integer NOT NULL,
    "Phone_number" text NOT NULL,
    "Email" text NOT NULL,
    "Address_tk" text NOT NULL,
    "Address_ru" text NOT NULL,
    "Address_en" text NOT NULL,
    "Address_tr" text NOT NULL
);


ALTER TABLE public."Addresses" OWNER TO pikiruser;

--
-- Name: Addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Addresses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Galleries; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Galleries" (
    "Id" integer NOT NULL,
    "Text_tk" text NOT NULL,
    "Text_ru" text NOT NULL,
    "Text_en" text NOT NULL,
    "Text_tr" text NOT NULL,
    "Url" text NOT NULL,
    "GalleryTypeId" integer
);


ALTER TABLE public."Galleries" OWNER TO pikiruser;

--
-- Name: Galleries_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Galleries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Galleries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GalleryTypes; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."GalleryTypes" (
    "Id" integer NOT NULL,
    "Type" text NOT NULL
);


ALTER TABLE public."GalleryTypes" OWNER TO pikiruser;

--
-- Name: GalleryTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."GalleryTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GalleryTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GeneralInfos; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."GeneralInfos" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Logo" text NOT NULL
);


ALTER TABLE public."GeneralInfos" OWNER TO pikiruser;

--
-- Name: GeneralInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."GeneralInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GeneralInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Images; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Images" (
    "Id" integer NOT NULL,
    "Page" text NOT NULL,
    "Type" integer NOT NULL,
    "Order" integer NOT NULL,
    "Url" text NOT NULL,
    "Name" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Images" OWNER TO pikiruser;

--
-- Name: Images_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Images" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Images_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: News; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."News" (
    "Id" integer NOT NULL,
    "Name_tk" text NOT NULL,
    "Name_ru" text NOT NULL,
    "Name_en" text NOT NULL,
    "Name_tr" text NOT NULL,
    "Text_tk" text NOT NULL,
    "Text_ru" text NOT NULL,
    "Text_en" text NOT NULL,
    "Text_tr" text NOT NULL,
    "Url" text NOT NULL,
    "Status" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."News" OWNER TO pikiruser;

--
-- Name: News_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."News" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."News_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pages; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Pages" (
    "Id" integer NOT NULL,
    "Type" text NOT NULL,
    "SubTitle_tk" text NOT NULL,
    "SubTitle_ru" text NOT NULL,
    "SubTitle_en" text NOT NULL,
    "Title_tk" text NOT NULL,
    "Title_ru" text NOT NULL,
    "Title_en" text NOT NULL,
    "Text_tk" text NOT NULL,
    "Text_ru" text NOT NULL,
    "Text_en" text NOT NULL,
    "Title_tr" text NOT NULL,
    "Text_tr" text NOT NULL,
    "SubTitle_tr" text NOT NULL,
    "Name" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Pages" OWNER TO pikiruser;

--
-- Name: Pages_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Pages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Payments; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Payments" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Payments" OWNER TO pikiruser;

--
-- Name: Payments_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Payments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name_tk" text NOT NULL,
    "Name_ru" text NOT NULL,
    "Name_en" text NOT NULL,
    "Name_tr" text NOT NULL,
    "Desc_tr" text NOT NULL,
    "Desc_tk" text NOT NULL,
    "Desc_ru" text NOT NULL,
    "Desc_en" text NOT NULL,
    "Dest_tk" text NOT NULL,
    "Dest_en" text NOT NULL,
    "Dest_ru" text NOT NULL,
    "Dest_tr" text NOT NULL,
    "Duration" text NOT NULL,
    "Price" integer NOT NULL,
    "People" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Url" text NOT NULL,
    "PaymentId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Products" OWNER TO pikiruser;

--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Services; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Services" (
    "Id" integer NOT NULL,
    "Name_tk" text NOT NULL,
    "Name_ru" text NOT NULL,
    "Name_en" text NOT NULL,
    "Name_tr" text NOT NULL,
    "Text_tk" text NOT NULL,
    "Text_ru" text NOT NULL,
    "Text_en" text NOT NULL,
    "Text_tr" text NOT NULL,
    "Order" integer NOT NULL,
    "Url" text NOT NULL
);


ALTER TABLE public."Services" OWNER TO pikiruser;

--
-- Name: Services_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Services" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Services_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sliders; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Sliders" (
    "Id" integer NOT NULL,
    "Url" text NOT NULL,
    "Text_tk" text NOT NULL,
    "Text_ru" text NOT NULL,
    "Text_en" text NOT NULL,
    "Text_tr" text NOT NULL,
    "Order" integer NOT NULL,
    "Title_en" text DEFAULT ''::text NOT NULL,
    "Title_ru" text DEFAULT ''::text NOT NULL,
    "Title_tk" text DEFAULT ''::text NOT NULL,
    "Title_tr" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Sliders" OWNER TO pikiruser;

--
-- Name: Sliders_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Sliders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sliders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO pikiruser;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Videos; Type: TABLE; Schema: public; Owner: pikiruser
--

CREATE TABLE public."Videos" (
    "Id" integer NOT NULL,
    "Type" integer NOT NULL,
    "Url" text NOT NULL
);


ALTER TABLE public."Videos" OWNER TO pikiruser;

--
-- Name: Videos_Id_seq; Type: SEQUENCE; Schema: public; Owner: pikiruser
--

ALTER TABLE public."Videos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Videos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Addresses; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Addresses" ("Id", "Phone_number", "Email", "Address_tk", "Address_ru", "Address_en", "Address_tr") FROM stdin;
3	+99363 243934	hoshsyyahat0710@gmail.com	Magtymguly köçesi 217, Gül Zemin söwda merkezi, ikinji gat.	улица Махтумкули 217, ТРЦ «Gül Zemin», второй этаж.	Magtymguly street 217, Gul Zemin shopping center, second floor.	Magtymguly caddesi 217, Gül Zemin alışveriş merkezi, ikinci kat.
4	+99361 727788	hoshsyyahat0710@gmail.com	Ataturk köçesi, 82, "Berkarar" söwda we dynç alyş merkezi, ikinji gat	улица Ататюрка 82, ТРЦ «Беркарар», второй этаж	Ataturk street 82, shopping center "Berkarar", second floor	Atatürk caddesi 82, "Berkarar" alışveriş merkezi , ikinci kat
8	+99361 585978	hoshsyyahat0710@gmail.com	G.Kuliýew köç. 71.	ул. Г. Кулиев 71	G.Kuliyev street 71.\n	G. Kuliyev caddesi. 71
7	+99362 463737	hoshsyyahat0710@gmail.com	G. Kuliýew köç. 88 (“Nowruz haly” binasy).	ул. Г. Кулиев 88 (здание “Nowruz haly”).	G. Kulyev street 88 (in the courtyard of the “Nowruz haly” building)	G. Kuliyev caddesi. 88 (“Nowruz haly” binasi).
\.


--
-- Data for Name: Galleries; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Galleries" ("Id", "Text_tk", "Text_ru", "Text_en", "Text_tr", "Url", "GalleryTypeId") FROM stdin;
7	Katalog	Каталог	Catalogue	Katalok	638549201344851872.png	\N
8					638549201503383893.png	\N
9					638549201575656208.png	\N
10					638549201651261965.jpeg	\N
11					638549201797190780.png	\N
12					638549202069233484.jpeg	\N
13					638549202152662809.png	\N
14					638549202378730297.jpg	\N
\.


--
-- Data for Name: GalleryTypes; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."GalleryTypes" ("Id", "Type") FROM stdin;
\.


--
-- Data for Name: GeneralInfos; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."GeneralInfos" ("Id", "Name", "Logo") FROM stdin;
1	hosh syyahat	638533146838458671.png
\.


--
-- Data for Name: Images; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Images" ("Id", "Page", "Type", "Order", "Url", "Name") FROM stdin;
7	index	2	7	638533622592038178.jpg	bash sahypa 7-nji surat
5	index	2	5	638533623889576618.png	bash sahypa 5-nji surat
6	index	2	6	638533624400170451.jpg	bash sahypa 6-njy surat
4	index	2	4	638533624968236925.png	bash sahypa 4-nji surat
9	about	1	1	638536268922872872.jpg	biz barada sahypa 1-nji surat
10	images	1	1	638536268983440503.jpg	suratlar sahypa 1-nji surat
11	packages	1	1	638536269270658175.jpg	turlar sahypa 1-nji surat
12	services	1	1	638536269322986348.jpg	hyzmatlar sahypa 1-nji surat
13	contact	1	1	638536269431610120.jpg	habarlashmak sahypa 1-nji surat
14	news	1	1	638536269498864791.jpg	tazeliker sahypa 1-nji surat
15	package	1	1	638536269554467016.jpg	tur maglumat sahypa 1QWEQWE12313-nji surat
1	index	2	1	638549198027591926.jpeg	bash sahypa 1-nji surat
2	index	2	2	638549199182575141.jpg	bash sahypa 2-nji surat
8	index	2	8	638549199891443461.jpeg	bash sahypa 8-nji surat
3	index	2	3	638552599015592640.webp	bash sahypa 3-nji surat
\.


--
-- Data for Name: News; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."News" ("Id", "Name_tk", "Name_ru", "Name_en", "Name_tr", "Text_tk", "Text_ru", "Text_en", "Text_tr", "Url", "Status", "CreatedAt") FROM stdin;
5	Aşgabat, Mary we Türkmenabat şäherlerinden «Awaza» boljak uçar gatnawlary artdyrylýar	Авиарейсов из Ашхабада, Мары и Туркменабата в направлении «Авазы» станет больше!	There will be more flights from Ashgabat, Mary and Turkmenabat in the direction of “Avaza”	Aşkabat, Meryem ve Türkmenabat'tan Avaza istikametine seferler artacak!	«Awaza» milli syýahatçylyk zolagynda dynç alyş möwsümleriniň başlanmagy bilen, «Türkmenistan» awiakompaniýasy açyk görnüşli paýdarlar jemgyýeti tarapyndan ýolagçylaryň artýan isleglerini kanagatlandyrmak üçin, Mary — Türkmenbaşy — Mary, Türkmenabat — Türkmenbaşy — Türkmenabat ugry boýunça goşmaça gatnawlar ýola goýuldy. Bu barada «Türkmenhowaýollary» agentliginiň resmi saýtynda habar berildi.\r\n\r\nHabarda bellenilişi ýaly, Aşgabat — Türkmenbaşy — Aşgabat ugry boýunça hem ýerine ýetirilýän gatnawlaryň sany hepdede 16 gatnawa çenli artdyryldy.	Авиакомпания «Туркменистан» увеличивает количество рейсов из Ашхабада, Мары и Туркменабата в направлении Туркменбаши. Об этом сообщает сайт агентства «Туркменховаёллары».\r\n\r\n«С началом сезона отдыха в национальной туристической зоне «Аваза», Акционерное общество открытого типа «Авиакомпания «Туркменистан» увеличила количество рейсов, чтобы удовлетворить возросший спрос пассажиров.\r\n\r\nБыли добавлены дополнительные рейсы по маршрутам Мары – Туркменбаши – Мары, Туркменабат – Туркменбаши – Туркменабат, а количество рейсов по маршруту Ашхабад – Туркменбаши – Ашхабад было увеличено до 16 в неделю», – говорится в сообщении.\r\n\r\nКроме того, в целях обеспечения качественного обслуживания пассажиров, агентство «Туркменховаёллары» провело комплекс подготовительных работ. Все международные аэропорты страны полностью оснащены необходимой наземной техникой и автотранспортом. Проверены системы освещения и связи взлетно-посадочных полос, работа служб управления воздушным движением. Персонал прошел обучение для предоставления высококлассного и культурного сервиса пассажирам, – отмечает источник.	“Turkmenistan” Airlines is increasing the number of flights from Ashgabat, Mary and Turkmenabat in the direction of Turkmenbashy. The website of the “Turkmenhowayollary” Agency reports this.\r\n\r\n“With the beginning of the holiday season in the “Avaza” national tourist zone, “Turkmenistan” Airlines Open Joint Stock Company increased the number of flights to meet the increased demand of passengers.\r\n\r\nAdditional flights were added on the routes Mary - Turkmenbashy - Mary, Turkmenabat - Turkmenbashy - Turkmenabat, and the number of flights on the route Ashgabat - Turkmenbashy - Ashgabat was increased to 16 per week”, - the message says.\r\n\r\nIn addition, in order to ensure high-quality passenger service, the “Turkmenhowayollary” Agency carried out a set of preparatory work. All international airports in the country are fully equipped with the necessary ground equipment and vehicles. The lighting and communication systems of the runways and the operation of air traffic control services were checked. The staff has been trained to provide high-quality and cultural service to passengers”, - the source notes.	Türkmenistan Hava Yolları Aşkabat, Mary ve Türkmenabat'tan Türkmenbaşı yönüne sefer sayısını artırıyor. Türkmenhowayollary ajansının web sitesi bunu bildiriyor.\r\n\r\n“Azaza ulusal turizm bölgesinde tatil sezonunun başlamasıyla birlikte Türkmenistan Havayolları Açık Anonim Şirketi, artan yolcu talebini karşılamak amacıyla sefer sayısını artırdı.\r\n\r\nMesajda, Meryem - Türkmenbaşı - Meryem, Türkmenabat - Türkmenbaşı - Türkmenabat güzergahına ilave seferler eklenerek, Aşkabat - Türkmenbaşı - Aşkabat güzergahındaki sefer sayısı da haftalık 16'ya çıkarıldı." ifadelerine yer verildi.\r\n\r\nAyrıca, yolculara yüksek kalitede hizmet verebilmek amacıyla Türkmenhowayollary acentesi bir dizi hazırlık çalışması yürüttü. Ülkedeki tüm uluslararası havalimanları gerekli yer ekipmanı ve araçlarla tam donanımlıdır. Pistlerin aydınlatma ve iletişim sistemleri ile hava trafik kontrol hizmetlerinin işleyişi kontrol edildi. Kaynak, personelin yolculara yüksek kaliteli ve kültürel hizmet sunmak üzere eğitildiğini belirtiyor.	638533630599111677.webp	t	2024-06-07 08:17:39.912085+00
6	Türkmenistan bilen Kataryň arasynda göni howa gatnawlaryny ýola goýmak meselesi ara alnyp maslahatlaşyldy	Туркменистан и Катар обсудили открытие прямых авиарейсов	Turkmenistan and Qatar discussed the opening of direct flights	Türkmenistan ve Katar, iki ülke arasında direkt uçuşların başlamasını görüştü	Aşgabat şäherinde «Türkmenhowaýollary» agentliginiň degişli ýolbaşçylary bilen Katar Döwletiniň Türkmenistandaky ilçihanasynyň işleri wagtlaýyn ynanylan wekili Al-Remaihi Ghanem Abdulla arasynda geçirilen duşuşykda ýakyn geljekde Türkmenistanyň we Kataryň arasynda göni howa gatnawlaryny ýola goýmak meselesi ara alnyp maslahatlaşyldy. Bu barada agentligiň resmi saýtynda habar berildi.\r\n\r\nGepleşiklerde göni we üstaşyr gatnawlary ýola goýmak mümkinçiligine aýratyn üns berildi. Hususan-da, Türkmenistanda «Qatar Airways» awiakompaniýasynyň ýerine ýetirýän howa gatnawlary, olaryň nyrhlary, hyzmatlary barada mahabatlandyryş işlerini geçirmegiň ýola goýulmagy teklip edildi.\r\n\r\nMundan başga-da, «Türkmenistan» awiakompaniýasy tarapyndan Aşgabat ― Doha ― Aşgabat aralygynda göni ýolagçy gatnawynyň ýola goýlan ýagdaýynda Kataryň halkara howa menzilleri tarapyndan ýeňillikleriň berilmegi we bu gatnawda üstaşyr ýolagçylaryň sanyny artdyrmak boýunça bilelikde işleri geçirmek barada hem teklipler berildi.\r\n\r\nŞol bir wagtyň özünde Katar döwletine gidýän Türkmenistanyň raýatlarynyň onlaýn wiza hyzmatyndan hem peýdalanyp biljekdikleri mälim edildi.\r\n\r\nUmuman aýdylanda, geçirilen gepleşikler Türkmenistanda raýat awiasiýasyny ösdürmek hem-de halkara gatnawlarynyň sanyny artdyrmak boýunça işleriň yzygiderli durmuşa geçiriljekdiginden habar berýär.	Открытие прямых авиарейсов между Туркменистаном и Катаром обсудили на встрече в Ашхабаде представители агентства «Туркменховаеллары» и временный поверенный в делах Государства Катар в Туркменистане Ганем Абдулла Аль-Ремаихи. Об этом сообщает официальный сайт агентства.\r\n\r\nОсобое внимание на переговорах было уделено возможности установления прямых и транзитных рейсов. Прозвучало предложение организовать рекламные акции авиакомпании Qatar Airways на территории Туркменистана, включая информирование о тарифах и услугах.\r\n\r\nТакже обсуждалось предоставление льгот катарскими аэропортами для рейса Ашхабад – Доха – Ашхабад туркменского национального авиаперевозчика, в случае его запуска, с целью увеличения транзитного пассажиропотока.\r\n\r\nОтмечено, что граждане Туркменистана смогут воспользоваться онлайн-сервисом для упрощенного оформления виз при поездках в Катар.\r\n\r\nВ целом, встреча подтвердила курс Туркменистана на дальнейшее развитие гражданской авиации и расширение международного авиасообщения.	The opening of direct flights between Turkmenistan and Qatar was discussed at a meeting in Ashgabat by representatives of the “Turkmenhowayollary” Agency and Charge d'Affaires of the State of Qatar in Turkmenistan Ghanem Abdullah Al-Rumaihi. The official website of the agency reports this.\r\n\r\nParticular attention at the negotiations was paid to the possibility of establishing direct and transit flights. There was a proposal to organize promotional campaigns for Qatar Airways in Turkmenistan, including information about tariffs and services.\r\n\r\nThe provision of benefits by Qatari airports for the Ashgabat-Doha-Ashgabat flight of the Turkmen national air carrier, in the event of its launch, was also discussed in order to increase transit passenger traffic.\r\n\r\nIt was noted that citizens of Turkmenistan will be able to use the online service for simplified visa processing when traveling to Qatar.\r\n\r\nIn general, the meeting confirmed Turkmenistan’s course towards the further development of civil aviation and the expansion of international air traffic.	Türkmenistan ile Katar arasında direkt uçuşların başlaması, Türkmen Hava Yolları’nın Katar’ın Türkmenistan'daki Maslahatgüzarı Ghanem bin Abdullah Al-Remaihi ile Aşkabat'ta yaptığı toplantıda değerlendirildi. Toplantının detayları, Türkmenistan Hava Yolları’nın internet sitesinde yer aldı.\r\n\r\nMüzakerelerde doğrudan ve transit uçuşların başlaması ihtimali üzerinde özellikle duruldu. Qatar Airways için Türkmenistan'da tarifeler ve hizmetler hakkında bilgi içeren reklam kampanyaları düzenlenmesi teklif edildi.\r\n\r\nTransit yolcu trafiğinin artırılması amacıyla, Türkmen Hava Yolları’nın Aşkabat-Doha-Aşgabat seferlerinin başlaması durumunda Katar’daki havalimanlarından yararlanılmasına da değinildi.\r\n\r\nTürkmen vatandaşlarının Katar'a seyahat ederken vize işlemlerini kolaylaştırmak için çevrimiçi hizmetlerden yararlanabilecekleri kaydedildi.\r\n\r\nToplantı genel olarak Türkmenistan'ın sivil havacılığın daha da geliştirilmesi ve uluslararası hava trafiğinin genişletilmesi yönündeki hedeflerini doğruladı.	638533631924293514.webp	t	2024-06-07 08:19:52.430288+00
7	«Türkmenistan» awiakompaniýasy Kuala-Lumpur şäherine goşmaça uçuşa başlady	Туркменские авиалинии запустили дополнительный рейс в Куала-Лумпур	Turkmenistan Airlines launched an additional flight to Kuala Lumpur	Türkmen Hava Yolları, Kuala Lumpur'a ek sefer başlattı	«Türkmenistan» awiakompaniýasy maý aýynyň başyndan Aşgabat — Kuala-Lumpur — Aşgabat ugurlarynda goşmaça hepdelik uçuşa başlady. Bu barada awiakompaniýasynyň resmi saýtynda habar berildi.\r\n\r\nTäze uçuş her sişenbe güni amala aşyrylar we türkmen howa ýollarynyň Malaýziýanyň paýtagtyna gatnawlarynyň ýygylygyny artdyrar. Goşmaça uçuşy ýola goýmak karary iki ýurduň arasyndaky barha artýan howa syýahatyna bolan islegi kanagatlandyrmak üçin kabul edildi.\r\n\r\nturkmenistanairlines.tm web sahypasyna görä, Aşgabat — Kuala-Lumpur ugry boýunça peteginiň bahasy 7 müň TMT. Yzyna gaýdyp gelýän uçuş üçin petegiň bahasy 7 müň 35,8 TMT.	Авиакомпания «Туркменистан» с начала мая запустила дополнительный еженедельный рейс по маршруту Ашхабад – Куала-Лумпур – Ашхабад, сообщается на сайте авиаперевозчика.\r\n\r\nНовый рейс будет выполняться каждый вторник, увеличивая частоту полетов туркменской авиакомпании в столицу Малайзии. Решение о запуске дополнительного рейса было принято в целях удовлетворения растущего спроса на авиаперевозки между двумя странами.\r\n\r\nСтоимость одностороннего билета Ашхабад – Куала-Лумпур на сайте turkmenistanairlines.tm — 7 тыс. ТМТ. Билет на обратный рейс обойдется туристам в 7 тыс. 35,8 ТМТ.	“Turkmenistan” Airlines has launched an additional weekly flight on the Ashgabat – Kuala Lumpur – Ashgabat route from the beginning of May, according to the airline’s website.\r\n\r\nThe new flight will operate every Tuesday, increasing the frequency of flights of the Turkmen airline to the capital of Malaysia. The decision to launch an additional flight was made in order to meet the growing demand for air travel between the two countries.\r\n\r\nThe cost of a one-way ticket Ashgabat - Kuala Lumpur on the website turkmenistanairlines.tm is 7 thousand TMT. A return flight ticket will cost tourists 7 thousand 35,8 TMT.	Türkmen Hava Yolları’nın resmi internet sitesinden yapılan açıklamaya göre, Mayıs ayının başından itibaren Aşkabat – Kuala Lumpur – Aşkabat güzergahında ek bir uçuş başlatıldı.\r\n\r\nYeni ek uçuş her Salı günü gerçekleştirilecek ve Türkmen Hava Yolları’nın Malezya'nın başkentine olan uçuşlarının sıklığı artırılacak. İki ülke arasında artan yolcu talebini karşılamak amacıyla ek uçuşun konulması kararı alındı.\r\n\r\nHava Yolu şirketinin resmi internet sitesi turkmenistanairlines.tm’de yer alan Aşkabat - Kuala Lumpur arası tek yön uçak biletin ücreti 7 bin TMT, gidiş-dönüş uçak biletinin fiyatı ise 7035,8 TMT olarak belirtildi.	638533634060492847.jpg	t	2024-06-07 08:23:26.050465+00
\.


--
-- Data for Name: Pages; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Pages" ("Id", "Type", "SubTitle_tk", "SubTitle_ru", "SubTitle_en", "Title_tk", "Title_ru", "Title_en", "Text_tk", "Text_ru", "Text_en", "Title_tr", "Text_tr", "SubTitle_tr", "Name") FROM stdin;
5	index_images	PURSATLAR	МОМЕНТЫ	MOMENTS	GEZELENÇLERDEN SURATLAR	ФОТО ИЗ ПУТЕШЕСТВИЙ	PHOTOS FROM TRAVELS				SEÝAHATLERDEN FOTOĞRAFLAR		ANILAR	Baş sahypa (suratlar bölümi)
7	foot_about				BIZ BARADA	О НАС	ABOUT US	Biziň üçin myhmansöýerlik durmuşyň özenidir we söwda etmegiň usulydyr!	Для нас гостеприимство – это суть жизни и способа ведения бизнеса!	For us, hospitality is the essence of life and the way we do business!	HAKKIMIZDA	Bizim için misafirperverlik yaşamın ve iş yapma şeklimizin özüdür!		Footer sahypa (biz barada bölümi)
6	index_news	TÄZELIKLER	НОВОСТИ	NEWS	IŇ SOŇKYLAR	ПОСЛЕДНИЕ	THE LATEST				EN SON		HABERLER	Baş sahypa (Täzelikler bölümi)
8	foot_contact				HABARLAŞMAK ÜÇIN	ПО ВОПРОСАМ	FOR QUESTIONS	Şeýle hem, biziň bilen habarlaşyp bilersiňiz	Вы также можете связаться с нами	You can also contact us	İLETİŞİM İÇİN	Ayrıca bizimle iletişime geçebilirsiniz		Footer sahypa (habarlaşmak bölümi)
4	index_travel	Syýahat	Путешествие	Travel	SYÝAHAT EDIP BIZI ÝADA SAL	ПУТЕШЕСТВУЙТЕ. ОБНАРУЖИВАЙТЕ. ПОМНИТЕ НАС!!	TRAVEL. DISCOVER. REMEMBER US!!	«HOŞ SYÝAHAT» sizi Türkmenistanda garşy alýar we Aşgabatda onuň töwereginde hünärmen syýahatçylarymyz we sürüjilerimiz bilen gezelençleri hödürlemekden hoşal.	«HOŞ SYÝAHAT» приветствует вас в Туркменистане и рада предложить туры по Ашхабаду и его окрестностям с нашими профессиональными гидами и водителями.	«HOŞ SYÝAHAT» welcomes you to Turkmenistan and is pleased to offer tours in and around Ashgabat with our professional tour guides and drivers.	SEÝAHATE GİT. KEŞFET. BİZİ HATIRLA!!	«HOŞ SYÝAHAT» sizi Türkmenistan'da karşılıyor ve profesyonel tur rehberlerimiz ve şoförlerimizle Aşkabat ve çevresinde turlar sunmaktan mutluluk duyuyor.	Seýahat	Baş sahypa (syýahat bölümi)
3	index_package	UGURLAR	НАПРАВЛЕНИЯ	DIRECTIONS	TURLAR	ТУРЫ	TOURS	Tejribäni paýlaşmak ýaly möhüm zat, baryp görýän ýerlerimiziň edýän işlerimizden peýdalanmagyny üpjün etmekdir. Şol sebäpden, ýerli çeşmeleri ulanmak, ýerli ýolbeletleri we ulaglary ulanmak, senetçiler we kiçi kärhanalar bilen hyzmatdaşlyk edýän ýerimize mümkin boldugyça köp maýa goýmak üçin aýratyn ähmiýete eýe bolýarys.	Не менее важно, чем делиться опытом, обеспечить, чтобы места, которые мы посещаем, получали пользу от того, что мы делаем. Вот почему мы придаем большое значение использованию местных ресурсов, использованию местных гидов и транспортных средств, а также максимальному инвестированию в места, где мы сотрудничаем с ремесленниками и малым бизнесом.	Just as important as sharing the experience is ensuring that the places we visit benefit from what we do. That's why we place great importance on using local resources, using local guides and vehicles, and investing as much as possible in the places we collaborate with artisans and small businesses.	TURLAR	Tecrübeyi paylaşmak kadar, gezdiğimiz yerlerin de yaptıklarımızdan faydalanmasını sağlamak da önemli. Bu nedenle yerel kaynakları kullanmaya, yerel rehber ve araçları kullanmaya, esnaf ve küçük işletmelerle iş birliği yaptığımız yerlere mümkün olduğunca yatırım yapmaya büyük önem veriyoruz.	ÝÖNLER	Baş sahypa (turlar bölümi)
13	contact_about	HABARLAŞMAK	COMMUNICATION	FOR QUESTIONS	GOŞMAÇA MAGLUMATLAR ÜÇIN BIZIŇ BILEN HABARLAŞYP BILERSIŇIZ	ДЛЯ ПОЛУЧЕНИЯ БОЛЕЕ ПОДРОБНОЙ ИНФОРМАЦИИ СВЯЖИТЕСЬ С НАМИ	CONTACT WITH US FOR MORE INFORMATIONS				DAHA FAZLA BİLGİ İÇİN BİZE ULAŞA BİLİRSİNİZ		İLETİŞİM	Habarlaşmak sahypa (biz barada bölümi)
9	about_about	BIZ BARADA	О НАС	ABOUT US	TÜRKMENISTANDA SYÝAHAT ETMEK ÜÇIN YGTYBARLY HYZMATDAŞYŇYZ	ВАШ НАДЕЖНЫЙ ПАРТНЕР ДЛЯ ПУТЕШЕСТВИЙ ПО ТУРКМЕНИСТАНУ	YOUR RELIABLE PARTNER FOR TRAVELING IN TURKMENISTAN	Türkmenistandaky Türk Howaýollarynyň ygtyýarly wekili hökmünde «HOŞ SYÝAHAT», şu ýylyň ýanwar aýyndan başlap Türkiýe ýurdundaky iň uly howa gatnawy üçin bilet satýar. Munuň netijesinde Türkmenistanyň syýahat edýän raýatlary Stambul şäheriniň üsti bilen bütin dünýäde tranzit gatnawlaryny amala aşyrmaga mümkinçiligi bar.	Будучи уполномоченным представителем Turkish Airlines в Туркменистане, «HOŞ SYÝAHAT» с января текущего года занимается продажей билетов крупнейшей авиакомпании Турции. В результате у путешествующих граждан Туркменистана появилась возможность путешествовать по миру транзитом через город Стамбул.	As the authorized representative of Turkish Airlines in Turkmenistan, «HOŞ SYÝAHAT» has been selling tickets for the largest airline in Turkey since January of this year. As a result, the traveling citizens of Turkmenistan have the opportunity to transit around the world through the city of Istanbul	TÜRKMENİSTAN'DA SEYAHATLERDE GÜVENİLİR ORTAĞINIZ	Türk Hava Yolları'nın Türkmenistan'daki yetkili temsilcisi «HOŞ SYÝAHAT», bu yılın Ocak ayından bu yana Türkiye'nin en büyük havayolu şirketinin bilet satışını gerçekleştiriyor. Sonuç olarak, Türkmenistan'ın seyahat eden vatandaşları İstanbul şehri üzerinden dünyanın her yerine geçiş yapma fırsatına sahip oluyor	HAKKIMIZDA	Biz barada sahypa (Biz barada bölümi)
2	index_about	Biz barada	О нас	About us	Türkmenistanda syýahat etmek üçin ygtybarly hyzmatdaşyňyz!	Ваш надежный туристический партнер в Туркменистане!	Your reliable travel partner in Turkmenistan!	Türkmenistandaky Türk Howaýollarynyň ygtyýarly wekili hökmünde «HOŞ SYÝAHAT», şu ýylyň ýanwar aýyndan başlap Türkiýe ýurdundaky iň uly howa gatnawy üçin bilet satýar. Munuň netijesinde Türkmenistanyň syýahat edýän raýatlary Stambul şäheriniň üsti bilen bütin dünýäde tranzit gatnawlaryny amala aşyrmaga mümkinçiligi bar.	Будучи уполномоченным представителем Turkish Airlines в Туркменистане, «HOŞ SYÝAHAT» с января текущего года занимается продажей билетов крупнейшей авиакомпании Турции. В результате у путешествующих граждан Туркменистана появилась возможность путешествовать по миру транзитом через город Стамбул.	As the authorized representative of Turkish Airlines in Turkmenistan, «HOŞ SYÝAHAT» has been selling tickets for the largest airline in Turkey since January of this year. As a result, the traveling citizens of Turkmenistan have the opportunity to transit around the world through the city of Istanbul	Türkmenistan'daki güvenilir seyahat ortağınız!	Türk Hava Yolları'nın Türkmenistan'daki yetkili temsilcisi «HOŞ SYÝAHAT», bu yılın Ocak ayından bu yana Türkiye'nin en büyük havayolu şirketinin bilet satışını gerçekleştiriyor. Sonuç olarak, Türkmenistan'ın seyahat eden vatandaşları İstanbul şehri üzerinden dünyanın her yerine geçiş yapma fırsatına sahip oluyor	Hakkımızda	Baş sahypa (biz barada bölümi)
\.


--
-- Data for Name: Payments; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Payments" ("Id", "Name") FROM stdin;
1	USD
2	TL
3	TMT
4	EURO
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Products" ("Id", "Name_tk", "Name_ru", "Name_en", "Name_tr", "Desc_tr", "Desc_tk", "Desc_ru", "Desc_en", "Dest_tk", "Dest_en", "Dest_ru", "Dest_tr", "Duration", "Price", "People", "Rating", "Url", "PaymentId") FROM stdin;
7	5 günlük Türkmenistan syýahatçylyk maksatnamasy.	Туркменистан туристическая программа на 5 дней.	Turkmenistan tourist program for 5 days.	5 günlük Türkmenistan turizm programı.	5 günlük Türkmenistan turizm programı.\r\n1. Gün: Aşkabat uluslararası havaalanında buluşma, otele giriş, müzeye ve M.Ö. IV-II. binyılın tarihi Nisa şehrine gezi.\r\n2 gün. Ahal Teke Hipodromu'na gezi, Aşkabat çevresinde gezi.\r\n3. Gün: Tarihi bir şehir ve MÖ 5. - 2. yüzyıllara ait kaleler olan Kunyaurgench'e hareket. e. otele giriş yapmak.\r\n4. Gün: Yurtlarda ulusal tarzda geceleme Darvaza'ya (Gaz Krateri) hareket.\r\n5. Gün: Çarşı ve alışveriş merkezi gezisi, havalimanından ayrılış.	5 günlük Türkmenistan syýahatçylyk maksatnamasy.\r\n1. Gün: Aşgabat halkara howa menzilinde ýygnak, myhmanhanada giriş, muzeýe gezelenç we miladydan öňki müňýyllyk Nisa IV-II taryhy şäher Nisa.\r\n2. Gün. Ahal Teke aýlawyna ekskursiýa, Aşgabatda gezelenç.\r\n3. Gün: beöň 5-2-nji asyrlaryň taryhy şäheri we galalary bolan Kunyaurgenç şäherine gitmek. e. myhmanhanada barlaň.\r\n4. Gün: Bir gije Darwaza (Gas Crater), milli stilde öýlerde ýola çykmak.\r\n5. Gün: Bazara we söwda merkezine gezelenç, howa menziline gitmek.	Туркменистан туристическая программа на 5 дней.\r\n1. День: Встреча в международном аэропорту Ашхабада , заселение в отель, экскурсия по музею и историческому городу Ниса IV- II тыс. до н.э.\r\n2. День. Экскурсия в Ахал текинский ипподром, экскурсия по Ашхабаду.\r\n3. День: Выезд в Куняургенч исторический город и крепости V - II века до н. э. заселение в отель.\r\n4. День: Выезд в Дарваза ( Газовый Кратер) ночовка в национальном стиле в юртах.\r\n5. День: Экскурсия по базару и торговому центру, отправка проводы в аэропорту.	Turkmenistan tourist program for 5 days.\r\n1. Day: Meeting at the Ashgabat international airport, check-in at the hotel, excursion to the museum and historical city of Nisa IV-II millennium BC.\r\n2. Day. Excursion to Ahal Teke hippodrome, excursion around Ashgabat.\r\n3. Day: Departure to Kunyaurgench, a historical city and fortresses of the 5th - 2nd centuries BC. e. check in hotel.\r\n4. Day: Departure to Darvaza (Gas Crater) overnight in national style in yurts.\r\n5. Day: Excursion to the bazaar and shopping center, departure at the airport.	Ahal Teke aýlawyna ekskursiýa, Aşgabatda gezelenç.	Excursion to Ahal Teke hippodrome, excursion around Ashgabat.	Экскурсия в Ахал текинский ипподром, экскурсия по Ашхабаду.	Ahal Teke Hipodromu'na gezi, Aşkabat çevresinde gezi.	/	850	1	1	638533165872969803.jpg	1
4	5 günlük Türkmenistan syýahatçylyk maksatnamasy.	Туркменистан туристическая программа на 5 дней.	Turkmenistan tourist program for 5 days.	5 günlük Türkmenistan turizm programı.	5 günlük Türkmenistan turizm programı.\r\n1. Gün: Farap sınırında buluşma, Meryem'e hareket, otele yerleşme.\r\n2 gün. Merv'in tarihi şehri ve kaleleri Meryem'e gezi, hareket\r\nAşkabat, otele giriş.\r\n3. Gün: Aşkabat ve tarihi Nisa şehri ve kaleleri gezisi, hareket\r\nDarvaza'da (Gaz Krateri) yurtlarda ulusal tarzda bir geceleme.\r\n4. Tarihi bir şehir ve MÖ 5. - 2. yüzyıllara ait kaleler olan Kunyaurgench'e hareket. e.\r\notele giriş yapmak.\r\n5. Gün: Daşoğuz sınır kapısı Şavat'a transfer.\r\n Tur masrafları.\r\n	Türkmenistan 5 günlük syýahatçylyk maksatnamasy.\r\n1. Gün: Farap serhedinde duşuşyk, Mary şäherine gitmek, myhmanhanada giriş.\r\n2. Gün. Merýemiň taryhy şäheri we galalary bolan Merýeme gezelenç, gitmek\r\nAşgabat, myhmanhanada giriş.\r\n3. Gün: Aşgabadyň töweregine gezelenç, we Nisa şäheriniň taryhy şäheri we galalary\r\nDarwazada (Gas Crater) bir gije howlularda milli stilde.\r\n4. Taryhy şäher we beöň 5-2-nji asyr galalary bolan Kunyaurgenç şäherine gitmek. e.\r\nmyhmanhanada barlaň.\r\n5. Gün: Daşoguz serhet barlag nokadyna “Şawat” geçiriň.\r\n Syýahat çykdajylary.\r\n	Туркменистан туристическая программа на 5 дней.\r\n1. День: Встреча на границе Фарап, выезд в Мары, заселение в отель.\r\n2. День. Экскурсия в Мары исторический город и крепости Мерв, Выезд в Ашхабад, заселение в отель.\r\n3. День: Экскурсия по Ашхабаду, и исторический город и крепости Ниса, Выезд в Дарваза (Газовый Кратер) ночовка в национальном стиле в юртах.\r\n4. Выезд в Куняургенч исторический город и крепости V - II века до н. э. заселение в отель.\r\n5. День: Отправка на границу Дашогуза пункт пропуска «Шават».\r\n 	Turkmenistan tourist program for 5 days.\r\n1. Day: Meeting at the Farap border, departure to Mary, check-in at the hotel.\r\n2. Day. Excursion to Mary, the historical city and fortresses of Merv, Departure to\r\nAshgabat, check-in at the hotel.\r\n3. Day: Excursion around Ashgabat, and the historical city and fortresses of Nisa, Departure\r\nin Darvaza (Gas Crater) overnight in national style in yurts.\r\n4. Departure to Kunyaurgench, a historical city and fortresses of the 5th - 2nd centuries BC. e.\r\ncheck in hotel.\r\n5. Day: Transfer to the Dashoguz border checkpoint “Shavat”.\r\n	Farap serhedinde duşuşyk, Mary şäherine gitmek, myhmanhanada giriş.	Excursion to Mary, the historical city and fortresses of Merv, Departure to Ashgabat, check-in at the hotel.	Экскурсия в Мары исторический город и крепости Мерв, Выезд в Ашхабад, заселение в отель.	Farap sınırında buluşma, Meryem'e hareket, otele yerleşme.	/	850	1	5	638533163121539115.jpg	1
9	7 günlük Türkmenistan syýahatçylyk maksatnamasy.	Туркменистан туристическая программа на 7 дней.	Turkmenistan tourist program for 7 days.	7 gün boyunca Türkmenistan turizm programı.	7 gün boyunca Türkmenistan turizm programı.\r\n1. Gün: Havaalanında buluşma, otele yerleşme, müze turu ve M.Ö. IV-II. binyıllara ait tarihi Nisa kenti. 2. Gün: MÖ 5. - 2. yüzyıllara ait tarihi bir şehir ve kale olan Kunyaurgench'e hareket. e. otele giriş yapmak.\r\n3. Gün: Yurtlarda ulusal tarzda geceleme Darvaza'ya (Gaz Krateri) hareket. 4. Gün: MÖ 3. binyıl sonu - 2. binyıl başı tarihi Merv kentini gezmek için Meryem Ana'ya hareket. e.\r\n5. Gün: Balkanabad'a transit olarak Aşkabat'a hareket ve geceleme otelde.\r\n6. Gün: Yangi-Kala kanyonuna gezi, ardından Aşkabat'a hareket ve geceleme otelde.\r\n7. Gün: Çarşı ve alışveriş merkezi gezisi, havalimanından ayrılış.	7 günlük Türkmenistan syýahatçylyk maksatnamasy.\r\n1. Gün: Aeroportda duşuşyk, myhmanhanada giriş, muzeýe gezelenç we miladydan öňki müňýyllyk Nisa IV-II taryhy şäher. \r\n2. Gün: beöň 5-2-nji asyrlaryň taryhy şäheri we galalary bolan Kunyaurgenç şäherine gitmek. e. myhmanhanada barlaň.\r\n3. Gün: Derwaza (Gas Crater) gijeki öýlerde milli stilde gitmek. \r\n4. Gün: taryhy Merw şäherine gezelenç etmek üçin miladydan öňki 3-nji asyryň ahyry - 2-nji müňýyllygyň başynda Mary şäherine gitmek. e.\r\n5. Gün: Balkanabada tranzit bilen Aşgabat şäherine gitmek we myhmanhanada bir gije.\r\n6. Gün: iaňi-Kala kanýonyna ekskursiýa, soňra Aşgabat şäherine we bir gije myhmanhanada gitmek.\r\n7. Gün: Bazara we söwda merkezine gezelenç, howa menziline gitmek.	Туркменистан туристическая программа на 7 дней.\r\n1. День: Встреча в аэропорту, заселение в отель, экскурсия по музею и историческому городу Ниса IV- II тыс. до н.э. 2. День: Выезд в Куняургенч исторический город и крепости V - II века до н. э. заселение в отель.\r\n3. День: Выезд в Дарваза ( Газовый Кратер) ночовка в национальном стиле в юртах. 4. День: Выезд в Мары экскурсия по историческому городу Мерв конец 3-го — начало 2-го тысячелетия до н. э.\r\n5. День: Выезд в Ашхабад транзитом в Балканабад ночовка в отеле.\r\n6. День: Экскурсия по каньону Янги-Кала, далее выезд в Ашхабад ночовка в отеле.\r\n7. День: Экскурсия по базару и торговому центру, отправка проводы в аэропорту.	Turkmenistan tourist program for 7 days.\r\n1. Day: Meeting at the airport, check-in at the hotel, tour of the museum and historical city of Nisa IV-II millennium BC. \r\n2. Day: Departure to Kunyaurgench, a historical city and fortresses of the 5th - 2nd centuries BC. e. check in hotel.\r\n3. Day: Departure to Darvaza (Gas Crater) overnight in national style in yurts. 4. Day: Departure to Mary for a tour of the historical city of Merv, late 3rd - early 2nd millennium BC. e.\r\n5. Day: Departure to Ashgabat with transit to Balkanabad and overnight at the hotel.\r\n6. Day: Excursion to the Yangi-Kala canyon, then departure to Ashgabat and overnight at a hotel.\r\n7. Day: Excursion to the bazaar and shopping center, departure at the airport.	Derwaza (Gas Crater) gijeki öýlerde milli stilde gitmek. 	Departure to Darvaza (Gas Crater) overnight in national style in yurts.	 Выезд в Дарваза ( Газовый Кратер) ночовка в национальном стиле в юртах. 4. День: Выезд в Мары экскурсия по историческому городу Мерв конец 3-го — начало 2-го тысячелетия до н. э.	Yurtlarda ulusal tarzda geceleme Darvaza'ya (Gaz Krateri) hareket. 4. Gün: MÖ 3. binyıl sonu - 2. binyıl başı tarihi Merv kentini gezmek için Meryem Ana'ya hareket. e.	/	850	1	1	638533173582642519.jpg	1
8	7 günlük Türkmenistan syýahatçylyk maksatnamasy.	Туркменистан туристическая программа на 7 дней.	Turkmenistan tourist program for 7 days.	7 gün boyunca Türkmenistan turizm programı.	7 gün boyunca Türkmenistan turizm programı.\r\n1. Gün: Havaalanında buluşma, otele yerleşme, müze turu ve M.Ö. IV-II. binyıllara ait tarihi Nisa kenti. ayrıca tarihi Seyit Cemal-etdin kalesi \r\n2. Gün: Meryem'e hareket, tarihi Merv şehrine gezi, MÖ 3. binyıl sonu - 2. binyıl başı. ah..\r\n3. Gün: Lebap'a hareket, Köytendağ'a gezi ve kamp alanında geceleme.\r\n4. Gün: Köytendağ gezisi (dinozor izleri).\r\n5. Gün: Aşkabat'a hareket, otele yerleşme.\r\n6. Gün: Ahal çevresinden Nokhur dağlarına gezi, ardından Aşkabat'a hareket ve geceleme otelde.\r\n7. Gün: Çarşı ve alışveriş merkezi gezisi, havalimanından ayrılış.	7 günlük Türkmenistan syýahatçylyk maksatnamasy.\r\n1. Gün: Aeroportda duşuşyk, myhmanhanada giriş, muzeýe gezelenç we miladydan öňki müňýyllyk Nisa IV-II taryhy şäher. mundan başga-da, Seýit Jamal-etdiniň taryhy gala\r\n2-nji gün: Mary şäherine gitmek, taryhy Merw şäherine gezelenç, miladydan öňki 3-nji asyryň ahyry - 2-nji müňýyllygyň başynda. hä ..\r\n3. Gün: Lebap şäherine gitmek, Koýtendaga gezelenç we bir gije düşelgede gezelenç.\r\n4. Gün: Koýtendaga gezelenç (dinozawr ýollary).\r\n5. Gün: Aşgabat şäherine gitmek, myhmanhanada giriş.\r\n6. Gün: Ahalyň töwereginde Nokhur daglaryna gezelenç, soňra Aşgabat şäherine we bir gijede myhmanhanada gezelenç.\r\n7. Gün: Bazara we söwda merkezine gezelenç, howa menziline gitmek.	Туркменистан туристическая программа на 7 дней.\r\n1. День: Встреча в аэропорту, заселение в отель, экскурсия по музею и историческому городу Ниса IV- II тыс. до н.э. далее историческая крепость Сейит Джамал-этдин\r\n2. День: : Выезд в Мары экскурсия по историческому городу Мерв конец 3-го — начало 2-го тысячелетия до н. э..\r\n3. День: Выезд в Лебап экскурсия в Койтендаг ночовка в кемпинге.\r\n4. День: Экскурсия в Койтендаг (следы динозавра).\r\n5. День: Выезд в Ашхабад, заселение в отель.\r\n6. День: Экскурсия по Ахалу в горы нохур, далее выезд в Ашхабад ночовка в отеле.\r\n7. День: Экскурсия по базару и торговому центру, отправка проводы в аэропорту.	Turkmenistan tourist program for 7 days.\r\n1. Day: Meeting at the airport, check-in at the hotel, tour of the museum and historical city of Nisa IV-II millennium BC. further, the historical fortress of Seyit Jamal-etdin \r\n2. Day: : Departure to Mary, excursion to the historical city of Merv, late 3rd - early 2nd millennium BC. uh..\r\n3. Day: Departure to Lebap, excursion to Koytendag and overnight at a campsite.\r\n4. Day: Excursion to Koytendag (dinosaur tracks).\r\n5. Day: Departure to Ashgabat, check-in at the hotel.\r\n6. Day: Excursion around Ahal to the Nokhur mountains, then departure to Ashgabat and overnight at a hotel.\r\n7. Day: Excursion to the bazaar and shopping center, departure at the airport.	Mary şäherine gitmek, taryhy Merw şäherine gezelenç, miladydan öňki 3-nji asyryň ahyry - 2-nji müňýyllygyň başynda. 	Departure to Mary, excursion to the historical city of Merv, late 3rd - early 2nd millennium BC. uh..	Выезд в Мары экскурсия по историческому городу Мерв конец 3-го — начало 2-го тысячелетия до н. э..	Meryem'e hareket, tarihi Merv şehrine gezi, MÖ 3. binyıl sonu - 2. binyıl başı. ah..	/	850	1	1	638533169041667398.jpg	1
\.


--
-- Data for Name: Services; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Services" ("Id", "Name_tk", "Name_ru", "Name_en", "Name_tr", "Text_tk", "Text_ru", "Text_en", "Text_tr", "Order", "Url") FROM stdin;
4	Myhmanhanalarda ýerleşdirmek!	Заселение в отели!	Check-in!	Giriş!	Aşgabatdaky we welaýatlardaky myhmanhanalarda ýerleşdirmek.	Заселение в отели города Ашхабад и других велаятов. 	Check-in at hotels in Ashgabat and other velayats.	Aşkabat ve diğer velayatlardaki otellere giriş yapın.	4	638533644008623559.jpg
6	"OLIMP" Myhmanhanasy Olimpiýa şäherçesi	Гостиница "ОЛИМП" Олимпийский городок	"OLIMP" Hotel Olimpiya city	"OLIMP" Hotel Olimpiya city	Bir otag $142 iki otag 174	Одноместный $143 двухместный $174	Single room $142 double room $174	Single room $142 double room $174	2	638549216850089622.jpg
3	Hoş geldiňiz!	Встреча!	Welcome!	Hoş geldiniz!	Aşgabat halkara howa menzilinde ýygnak, myhmanhana girmek.	Встреча в международном аэропорту Ашхабада , заселение в отель.	Meeting at Ashgabat International Airport, check-in to the hotel.	Aşkabat Uluslararası Havalimanı'nda buluşma, otele yerleşme.	3	638533644600271472.jpg
5	"SPORT" Myhmanhanasy Olimpiýa şäherçesi	"СПОРТ" Гостиница, Олимпийский городок	"SPORT" Hotel, Olimpiya city	"SPORT" Oteli	Bir otag $102 iki otag $174	Один номер $102 двухместный $174 	Single room $102 double room $174	10 ýyl Abadançylyk (Moskowskiý) köçesi, Olimpiýa şäherçesi	1	638549212869890703.jpg
\.


--
-- Data for Name: Sliders; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Sliders" ("Id", "Url", "Text_tk", "Text_ru", "Text_en", "Text_tr", "Order", "Title_en", "Title_ru", "Title_tk", "Title_tr") FROM stdin;
3	638536265238869928.jpg	SYÝAHAT ETMEK ÜÇIN SIZIŇ YGTYBARLY HYZMATDAŞYŇYZ!	ВАШ НАДЕЖНЫЙ ТУРИСТИЧЕСКИЙ ПАРТНЕР!	YOUR RELIABLE TRAVEL PARTNER!	GÜVENILIR SEYAHAT ORTAĞINIZ!	0	Hosh Syyahat	Хош Сыяхат	Hoş Syýahat	Hoş Siyahat
5	638555360829181784.jpg	SYÝAHAT ETMEK ÜÇIN SIZIŇ YGTYBARLY HYZMATDAŞYŇYZ!	ВАШ НАДЕЖНЫЙ ТУРИСТИЧЕСКИЙ ПАРТНЕР!	YOUR RELIABLE TRAVEL PARTNER!	SYÝAHAT ETMEK ÜÇIN SIZIŇ YGTYBARLY HYZMATDAŞYŇYZ!	0	Hosh Syyahat	Хош Сыяхат	Hoş syýahat	Hoş syýahat
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Users" ("Id", "FirstName", "LastName", "Username", "Email", "PasswordHash") FROM stdin;
1	travel	travel	travel	travel@gmail.com	$2a$11$F5FVMgKDNyeO5WvLtkDQeO1So7bumR4Q7CszqM.6bDaQpkMJtk6bO
\.


--
-- Data for Name: Videos; Type: TABLE DATA; Schema: public; Owner: pikiruser
--

COPY public."Videos" ("Id", "Type", "Url") FROM stdin;
2	2	638546913756010256.VOB
1	1	638548327638377644.mp4
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20230923064100_changeProduct	6.0.7
20230923100205_changegeneralinfo	6.0.7
20230923115553_changeslider	6.0.7
20230926061226_Services	6.0.7
20230926061851_ServiceEdit	6.0.7
20230926063918_ServiceRemoveUnique	6.0.7
20231019130345_AddNewTables	6.0.7
20231020065954_Address	6.0.7
20231020094314_EditPages	6.0.7
20231020114340_EditImages	6.0.7
20231023041425_Payment	6.0.7
\.


--
-- Name: Addresses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Addresses_Id_seq"', 8, true);


--
-- Name: Galleries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Galleries_Id_seq"', 14, true);


--
-- Name: GalleryTypes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."GalleryTypes_Id_seq"', 1, false);


--
-- Name: GeneralInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."GeneralInfos_Id_seq"', 1, true);


--
-- Name: Images_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Images_Id_seq"', 15, true);


--
-- Name: News_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."News_Id_seq"', 7, true);


--
-- Name: Pages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Pages_Id_seq"', 14, true);


--
-- Name: Payments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Payments_Id_seq"', 4, true);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 9, true);


--
-- Name: Services_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Services_Id_seq"', 6, true);


--
-- Name: Sliders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Sliders_Id_seq"', 5, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: Videos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: pikiruser
--

SELECT pg_catalog.setval('public."Videos_Id_seq"', 2, true);


--
-- Name: Addresses PK_Addresses; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id");


--
-- Name: Galleries PK_Galleries; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Galleries"
    ADD CONSTRAINT "PK_Galleries" PRIMARY KEY ("Id");


--
-- Name: GalleryTypes PK_GalleryTypes; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."GalleryTypes"
    ADD CONSTRAINT "PK_GalleryTypes" PRIMARY KEY ("Id");


--
-- Name: GeneralInfos PK_GeneralInfos; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."GeneralInfos"
    ADD CONSTRAINT "PK_GeneralInfos" PRIMARY KEY ("Id");


--
-- Name: Images PK_Images; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Images"
    ADD CONSTRAINT "PK_Images" PRIMARY KEY ("Id");


--
-- Name: News PK_News; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."News"
    ADD CONSTRAINT "PK_News" PRIMARY KEY ("Id");


--
-- Name: Pages PK_Pages; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Pages"
    ADD CONSTRAINT "PK_Pages" PRIMARY KEY ("Id");


--
-- Name: Payments PK_Payments; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "PK_Payments" PRIMARY KEY ("Id");


--
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: Services PK_Services; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Services"
    ADD CONSTRAINT "PK_Services" PRIMARY KEY ("Id");


--
-- Name: Sliders PK_Sliders; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Sliders"
    ADD CONSTRAINT "PK_Sliders" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: Videos PK_Videos; Type: CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Videos"
    ADD CONSTRAINT "PK_Videos" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Galleries_GalleryTypeId; Type: INDEX; Schema: public; Owner: pikiruser
--

CREATE INDEX "IX_Galleries_GalleryTypeId" ON public."Galleries" USING btree ("GalleryTypeId");


--
-- Name: IX_Products_PaymentId; Type: INDEX; Schema: public; Owner: pikiruser
--

CREATE INDEX "IX_Products_PaymentId" ON public."Products" USING btree ("PaymentId");


--
-- Name: Galleries FK_Galleries_GalleryTypes_GalleryTypeId; Type: FK CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Galleries"
    ADD CONSTRAINT "FK_Galleries_GalleryTypes_GalleryTypeId" FOREIGN KEY ("GalleryTypeId") REFERENCES public."GalleryTypes"("Id");


--
-- Name: Products FK_Products_Payments_PaymentId; Type: FK CONSTRAINT; Schema: public; Owner: pikiruser
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES public."Payments"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

